USB PD initial support
busy-app/busybar-firmware pull request #16
Opened 2024-12-23 19:15 UTC by nminaylov

2025-01-30 15:32 UTC, hedger requested changes
Address the comments please

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power.c
> +    };
why use single-field union?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +void power_usb_pd_get_capabilities(PowerUsbPd* pd, PowerUsbPdCapability* caps) {
check caps for null

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +PowerUsbPd* power_usb_pd_alloc(FuriMessageQueue** pd_queue) {
why return a second value through parameter, when it's a field in the returned object?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    if(pd->cc_line_level == 2) {
better use enums for values

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        if(pd->cc_line_level == 2) {
use enums for branches and currents?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        furi_semaphore_release(pd->tx_idle_sem);
check status before releasing?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        uint32_t cc1_state = (UCPD1->SR & UCPD_SR_TYPEC_VSTATE_CC1) >>
define a struct and parse using it?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +            if(type == 1) { // Capabilities
use enums?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        uint16_t header = (buf[1] << 8) | buf[0];
use a struct for parsing?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        if(type == 1) { // GoodCRC
use enums?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        if(type == 0) { // Fixed PDO
use enums?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        uint32_t obj = (buf[i * 4]) | (buf[i * 4 + 1] << 8) | (buf[i * 4 + 2] << 16) |
looks like a packed struct

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +            pd->caps.cap[pdo_num].is_fixed = true;
cache ptr to `&pd->caps.cap[pdo_num]` and reuse

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    uint16_t header = (PdDataRoleUFP << 8) | (pd->src_rev_id << 6) | (PdPowerRoleSnk << 5);
use union with packed struct?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    uint16_t header = (PdDataRoleUFP << 8) | (pd->src_rev_id << 6) | (PdPowerRoleSnk << 5);
use union with packed struct?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    uint16_t header = (PdDataRoleUFP << 8) | (pd->src_rev_id << 6) | (PdPowerRoleSnk << 5);
use union with packed struct?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power.c
> +        if(power->pd_capabilities.cap[i].is_fixed) {
cache &power->pd_capabilities.cap[i] and reuse for brevity

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power.c
> +            power_usb_pd_request_power(power->usb_pd, 9000, 0); // Request 9v, max current
at least validate that compatible profile is available

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +#include "stm32u5xx_ll_dma.h"
< >

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    PdOrdSetSOP1 = 1, // SOP'
fix naming in comments

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    ucpd_dma_cfg.TriggerMode = LL_DMA_TRIGM_BLK_TRANSFER;
repeated assignments over existing same values

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    LL_UCPD_SetTransWin(UCPD1, 0x09);
magics - use named #defines?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        if(pd->caps.cap[i].is_fixed == false) {
if (!...)

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +        furi_mutex_release(pd->cap_mutex);
use single return point and release mutex at it

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +            pd_send_request_fixed(pd, cap_id, current);
check return value?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +            pd_send_request_pps(pd, cap_id, voltage, current);
check return value?

2025-01-30 15:32 UTC, hedger commented on applications/services/power_simple/power_usb_pd_i.h
> +#define PDO_NUMBER_MAX 10
why 10? aren't there only 3 bits for profile number?

2025-01-30 15:52 UTC, nminaylov commented on applications/services/power_simple/power.c
> +    };
Reserved for other power message types (reboot mode, get power info, etc)

2025-01-30 15:56 UTC, nminaylov commented on applications/services/power_simple/power_usb_pd.c
> +PowerUsbPd* power_usb_pd_alloc(FuriMessageQueue** pd_queue) {
PowerUsbPd is private

2025-01-30 16:13 UTC, nminaylov commented on applications/services/power_simple/power_usb_pd.c
> +    PdOrdSetSOP1 = 1, // SOP'
It's original name
![изображение](https://github.com/user-attachments/assets/de3e4a2d-4e13-4c5e-a047-c683e27ad75f)

2025-01-30 16:16 UTC, nminaylov commented on applications/services/power_simple/power_usb_pd.c
> +    LL_UCPD_SetTransWin(UCPD1, 0x09);
Magic values from the datasheet - no defines for them

2025-01-30 19:37 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    PdOrdSetSOP1 = 1, // SOP'
🤯

2025-01-30 19:38 UTC, hedger commented on applications/services/power_simple/power_usb_pd.c
> +    LL_UCPD_SetTransWin(UCPD1, 0x09);
we can still name them? up to you

2025-02-05 15:12 UTC, nminaylov commented on applications/services/power_simple/power_usb_pd.c
> +            pd->caps.cap[pdo_num].is_fixed = true;
`&pd->caps.cap[pdo_num]` is anonymous struct inside `PowerUsbPdCapability` (&pd->caps)

2025-02-05 15:13 UTC, nminaylov commented on applications/services/power_simple/power_usb_pd.c
> +        if(pd->caps.cap[i].is_fixed == false) {
Comparing with a value is more readable in my opinion

2025-02-05 15:17 UTC, nminaylov commented on applications/services/power_simple/power.c
> +            power_usb_pd_request_power(power->usb_pd, 9000, 0); // Request 9v, max current
Not required for now, needs more complicated power service. Also all the chargers that have more than one capability support 9v mode

2025-02-10 12:44 UTC, hedger submitted a review, later dismissed

2025-02-10 12:58 UTC, hedger approved these changes

2025-02-10 12:58 UTC, merged